#!/bin/sh
#https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Dynamically_isolating_CPUs
command=$2

if [[ $command == "started" ]]; then
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-7,16-23
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-7,16-23
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-7,16-23
elif [[ $command == "release" ]]; then
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-31
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-31
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-31
fi